### ISSUE TITLE
Additional good test case for time_floor()

### ISSUE THREAD

**Issue by DavisVaughan** [vspinu/timechange#11]
I was impressed by timechange's ability to handle this edge case with flooring dates + DST. I didn't see a test for this edge case, but it might be worth adding, as it is a rare case where "midnight" doesn't exist in some time zones. In lubridate, the way `floor_date()` works essentially assumes that this midnight always exists, but I really like the `time_floor()` behavior with the implicit `roll_dst = "boundary"`

``` r
y <- as.POSIXct("2020-03-29 01:00:00", tz = "Asia/Beirut")

y
#> [1] "2020-03-29 01:00:00 EEST"

# DST spring forward happens at 2020-03-29 00:00:00 and they spring forward
# to hour 1
y - 1
#> [1] "2020-03-28 23:59:59 EET"


lubridate::floor_date(y, "day")
#> [1] NA

timechange::time_floor(y, "day")
#> [1] "2020-03-29 01:00:00 EEST"
```

<sup>Created on 2020-10-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by vspinu** [comment]
Thanks!
